branch-defaults:
  default:
    environment: personal-react-env
    group_suffix: null
  master:
    environment: react-app-env
environment-defaults:
  personal-react-env:
    branch: null
    repository: null
global:
  application_name: personal-react-elastic
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
